package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	_ "github.com/joho/godotenv/autoload"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go.mongodb.org/mongo-driver/mongo/readpref"

	"parishioner_management/internal/common"
	"parishioner_management/internal/components"
	configs "parishioner_management/internal/configs"
	gin_middleware "parishioner_management/internal/configs/gin/middleware"
	gin_routes "parishioner_management/internal/routes/gin"
	options_util "parishioner_management/internal/utils/options" // gin-swagger middleware

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	"parishioner_management/cmd/server/docs" // docs is generated by Swag CLI, you have to import it.
)

type server struct {
	options options_util.Options
}

func defaultOptions() options_util.Options {
	if err := godotenv.Load(); err != nil {
		log.Fatal("Error loading .env file")
	}

	return options_util.Options{
		MongoDBUrl:   os.Getenv(configs.EnvMongoDBUrl),
		Port:         os.Getenv(configs.EnvPort),
		JwtSecretKey: os.Getenv(configs.EnvJwtSecretKey),
		APIPrefix:    os.Getenv(configs.EnvAPIPrefix),
		Mode:         os.Getenv(configs.EnvMode),
	}
}

func (s *server) start(appContext components.AppContext) error {
	gin, err := s.createAndConfigGin(appContext)

	if err != nil {
		return err
	}

	// programmatically set swagger info
	docs.SwaggerInfo.Title = "Parishioner Management API"
	docs.SwaggerInfo.Description = "This is a Swagger Parishioner Management API server."
	docs.SwaggerInfo.Host = "http://localhost:8080"
	docs.SwaggerInfo.BasePath = "/api"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	gin_routes.RegisterAllModules(gin, appContext, s.options.APIPrefix)
	address := fmt.Sprintf(":%v", s.options.Port)
	gin.GET("/api-document/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return gin.Run(address)
}

func (s *server) createAndConfigGin(appContext components.AppContext) (*gin.Engine, error) {
	if s.options.Mode == "release" {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.Default()
	r.SetTrustedProxies(nil)
	// s.configLog(e)
	// s.configErrHandler(e)

	// setup response when routing not found
	r.NoRoute(func(c *gin.Context) {
		c.JSON(404, common.NewFullErrorResponse(http.StatusNotFound, nil, "page not found", "page not found", "PAGE_NOT_FOUND"))
	})

	if err := gin_middleware.RegisterMiddleware(r, appContext, s.options); err != nil {
		return nil, err
	}

	return r, nil
}

func main() {
	optionsServer := defaultOptions()
	ctx := context.Background()
	mongoDB, err := mongo.Connect(ctx, options.Client().ApplyURI(optionsServer.MongoDBUrl))

	if err != nil {
		log.Fatalln(err)
	}

	// test connection of db
	if err := mongoDB.Ping(ctx, readpref.Primary()); err != nil {
		log.Fatalln("database connection failed", err)
	}

	appContext := components.NewAppContext(mongoDB)
	server := &server{optionsServer}

	if err := server.start(appContext); err != nil {
		log.Fatalf("fail to start, err=%v", err)
	}
}
